# Generated by Django 4.1.5 on 2023-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('descargada', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
