# Generated by Django 4.1.5 on 2023-02-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0002_documentales_delete_pelicula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentales',
            new_name='Peliculas',
        ),
    ]
